// Compiled by ClojureScript 1.8.51 {:static-fns true, :optimize-constants true}
goog.provide('huiyin.components.jumbotron');
goog.require('cljs.core');
goog.require('garden.units');
goog.require('huiyin.variables');
goog.require('huiyin.data');
huiyin.components.jumbotron.render = (function huiyin$components$jumbotron$render(state){
var height = cljs.core.get_in.cljs$core$IFn$_invoke$arity$2((cljs.core.deref.cljs$core$IFn$_invoke$arity$1 ? cljs.core.deref.cljs$core$IFn$_invoke$arity$1(state) : cljs.core.deref.call(null,state)),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$viewport_DASH_size,cljs.core.cst$kw$height], null));
return new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$section$jumbotron,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$style,new cljs.core.PersistentArrayMap(null, 1, [cljs.core.cst$kw$height,height], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$h1,cljs.core.cst$kw$title.cljs$core$IFn$_invoke$arity$1(huiyin.data.messages)], null)], null);
});
huiyin.components.jumbotron.jumbotron_style = new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$$jumbotron,new cljs.core.PersistentArrayMap(null, 8, [cljs.core.cst$kw$display,cljs.core.cst$kw$flex,cljs.core.cst$kw$padding,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [(0),(garden.units.rem.cljs$core$IFn$_invoke$arity$1 ? garden.units.rem.cljs$core$IFn$_invoke$arity$1((1)) : garden.units.rem.call(null,(1)))], null)], null),cljs.core.cst$kw$align_DASH_items,cljs.core.cst$kw$center,cljs.core.cst$kw$justify_DASH_content,cljs.core.cst$kw$center,cljs.core.cst$kw$background,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, ["url(/images/home.jpg)",cljs.core.cst$kw$no_DASH_repeat,cljs.core.cst$kw$center,cljs.core.cst$kw$bottom], null)], null),cljs.core.cst$kw$background_DASH_size,cljs.core.cst$kw$cover,cljs.core.cst$kw$max_DASH_height,(garden.units.px.cljs$core$IFn$_invoke$arity$1 ? garden.units.px.cljs$core$IFn$_invoke$arity$1((1024)) : garden.units.px.call(null,(1024))),cljs.core.cst$kw$transition,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$all,huiyin.variables.transition_time], null)], null)], null),new cljs.core.PersistentVector(null, 2, 5, cljs.core.PersistentVector.EMPTY_NODE, [cljs.core.cst$kw$h1,new cljs.core.PersistentArrayMap(null, 4, [cljs.core.cst$kw$color,huiyin.variables.headline_color_invert,cljs.core.cst$kw$font_DASH_family,new cljs.core.PersistentVector(null, 6, 5, cljs.core.PersistentVector.EMPTY_NODE, ["\"A2 60 Display Regular\"","\"Arial Black\"","Arial","Helvetica","Verdana","sans-serif"], null),cljs.core.cst$kw$transform,"translateY(-50px)",cljs.core.cst$kw$text_DASH_align,cljs.core.cst$kw$center], null)], null)], null)], null);
huiyin.components.jumbotron.css = new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [huiyin.components.jumbotron.jumbotron_style], null);
